from setuptools import setup, find_packages

setup(
    name="whale1.0",
    version="1.0.0",
    description="Whale1.0 - Open Source Video Generation Foundation Model",
    author="Sean Lab",
    author_email="sean_lab@me.com",
    url="https://github.com/seanlab007/Whale1.0",
    packages=find_packages(),
    python_requires=">=3.10",
    install_requires=[
        "torch>=2.0.0",
        "torchvision",
        "diffusers>=0.30.0",
        "transformers>=4.40.0",
        "accelerate>=0.27.0",
        "safetensors>=0.4.0",
        "opencv-python>=4.8.0",
        "pillow>=10.0.0",
        "numpy>=1.24.0",
        "pyyaml>=6.0",
        "tqdm>=4.64.0",
        "av>=10.0.0",
        "imageio>=2.31.0",
        "imageio-ffmpeg>=0.4.9",
        "einops>=0.7.0",
    ],
    extras_require={
        "wan2.2": [],
        "cogvideo": ["sentencepiece"],
        "hunyuan": [],
        "ltx": [],
        "full": [
            "mediapipe",
            "face-alignment",
            "scipy",
            "scikit-image",
        ],
    },
    classifiers=[
        "Development Status :: 4 - Beta",
        "Intended Audience :: Developers",
        "Intended Audience :: Science/Research",
        "License :: OSI Approved :: Apache Software License",
        "Programming Language :: Python :: 3",
        "Topic :: Scientific/Engineering :: Artificial Intelligence",
        "Topic :: Multimedia :: Video",
    ],
)
